basePath: /
definitions:
  entity.Message:
    properties:
      text:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for using swagger with fiber.
  title: Swagger Example API
  version: "1.0"
paths:
  /messages:
    get:
      consumes:
      - application/json
      description: Fetches all messages. You can add more details here.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Message'
            type: array
      summary: Get messages
      tags:
      - messages
swagger: "2.0"
