basePath: /
definitions:
  entity.Message:
    properties:
      text:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: This is a sample server for using swagger with fiber.
  title: Swagger Example API
  version: "1.0"
paths:
  /path:
    get:
      consumes:
      - application/json
      description: Displayes the call that is made
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Message'
            type: array
      summary: Get Call
      tags:
      - messages
swagger: "2.0"
